export {default as Thesaurus} from './Thesaurus/Thesaurus';
export {default as TypeMaster} from './TypeMaster/TypeMaster';
export {default as TextOptimizer} from './TextOptimizer/TextOptimizer';
export {default as Quiz} from './Quiz/Quiz';
export {default as CU} from './ContactUs/ContactUs';
export {default as N} from './Notes/Notes';
export {default as NB} from './Navbar/NavBar';
export {default as P} from './Profile/Profile';
export {default as Main} from './Main/main';